package com.xxd.mappers;

import com.xxd.models.XxdCGroup;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdCGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_c_group",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_c_group (id, groupid, ",
        "manager_id, groupname, ",
        "description, notice, ",
        "homegroup, stat, proxynum)",
        "values (#{id,jdbcType=INTEGER}, #{groupid,jdbcType=VARCHAR}, ",
        "#{managerId,jdbcType=VARCHAR}, #{groupname,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{notice,jdbcType=VARCHAR}, ",
        "#{homegroup,jdbcType=VARCHAR}, #{stat,jdbcType=CHAR}, #{proxynum,jdbcType=SMALLINT})"
    })
    int insert(XxdCGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdCGroupSqlProvider.class, method="insertSelective")
    int insertSelective(XxdCGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, groupid, manager_id, groupname, description, notice, homegroup, stat, proxynum",
        "from xxd_c_group",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="groupid", property="groupid", jdbcType=JdbcType.VARCHAR),
        @Result(column="manager_id", property="managerId", jdbcType=JdbcType.VARCHAR),
        @Result(column="groupname", property="groupname", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="notice", property="notice", jdbcType=JdbcType.VARCHAR),
        @Result(column="homegroup", property="homegroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="proxynum", property="proxynum", jdbcType=JdbcType.SMALLINT)
    })
    XxdCGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdCGroupSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdCGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_c_group",
        "set groupid = #{groupid,jdbcType=VARCHAR},",
          "manager_id = #{managerId,jdbcType=VARCHAR},",
          "groupname = #{groupname,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "notice = #{notice,jdbcType=VARCHAR},",
          "homegroup = #{homegroup,jdbcType=VARCHAR},",
          "stat = #{stat,jdbcType=CHAR},",
          "proxynum = #{proxynum,jdbcType=SMALLINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdCGroup record);
}