package com.xxd.mappers;

import com.xxd.models.XxdCGoods;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdCGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_c_goods",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_c_goods (id, gid, ",
        "goodname, photo_id, ",
        "showmoney, stat, class_id)",
        "values (#{id,jdbcType=INTEGER}, #{gid,jdbcType=VARCHAR}, ",
        "#{goodname,jdbcType=VARCHAR}, #{photoId,jdbcType=VARCHAR}, ",
        "#{showmoney,jdbcType=REAL}, #{stat,jdbcType=CHAR}, #{classId,jdbcType=VARCHAR})"
    })
    int insert(XxdCGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdCGoodsSqlProvider.class, method="insertSelective")
    int insertSelective(XxdCGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, gid, goodname, photo_id, showmoney, stat, class_id",
        "from xxd_c_goods",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="gid", property="gid", jdbcType=JdbcType.VARCHAR),
        @Result(column="goodname", property="goodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="photo_id", property="photoId", jdbcType=JdbcType.VARCHAR),
        @Result(column="showmoney", property="showmoney", jdbcType=JdbcType.REAL),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="class_id", property="classId", jdbcType=JdbcType.VARCHAR)
    })
    XxdCGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdCGoodsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdCGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_c_goods",
        "set gid = #{gid,jdbcType=VARCHAR},",
          "goodname = #{goodname,jdbcType=VARCHAR},",
          "photo_id = #{photoId,jdbcType=VARCHAR},",
          "showmoney = #{showmoney,jdbcType=REAL},",
          "stat = #{stat,jdbcType=CHAR},",
          "class_id = #{classId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdCGoods record);
}