package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdCGroupArea;

public class XxdCGroupAreaSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group_area
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCGroupArea record) {
        BEGIN();
        INSERT_INTO("xxd_c_group_area");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getGroupId() != null) {
            VALUES("group_id", "#{groupId,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaId() != null) {
            VALUES("area_id", "#{areaId,jdbcType=VARCHAR}");
        }
        
        if (record.getStartdate() != null) {
            VALUES("startdate", "#{startdate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEnddate() != null) {
            VALUES("enddate", "#{enddate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStat() != null) {
            VALUES("stat", "#{stat,jdbcType=CHAR}");
        }
        
        if (record.getCause() != null) {
            VALUES("cause", "#{cause,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group_area
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCGroupArea record) {
        BEGIN();
        UPDATE("xxd_c_group_area");
        
        if (record.getGroupId() != null) {
            SET("group_id = #{groupId,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaId() != null) {
            SET("area_id = #{areaId,jdbcType=VARCHAR}");
        }
        
        if (record.getStartdate() != null) {
            SET("startdate = #{startdate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEnddate() != null) {
            SET("enddate = #{enddate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStat() != null) {
            SET("stat = #{stat,jdbcType=CHAR}");
        }
        
        if (record.getCause() != null) {
            SET("cause = #{cause,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}