package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdCGoods;

public class XxdCGoodsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCGoods record) {
        BEGIN();
        INSERT_INTO("xxd_c_goods");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getGid() != null) {
            VALUES("gid", "#{gid,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodname() != null) {
            VALUES("goodname", "#{goodname,jdbcType=VARCHAR}");
        }
        
        if (record.getPhotoId() != null) {
            VALUES("photo_id", "#{photoId,jdbcType=VARCHAR}");
        }
        
        if (record.getShowmoney() != null) {
            VALUES("showmoney", "#{showmoney,jdbcType=REAL}");
        }
        
        if (record.getStat() != null) {
            VALUES("stat", "#{stat,jdbcType=CHAR}");
        }
        
        if (record.getClassId() != null) {
            VALUES("class_id", "#{classId,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCGoods record) {
        BEGIN();
        UPDATE("xxd_c_goods");
        
        if (record.getGid() != null) {
            SET("gid = #{gid,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodname() != null) {
            SET("goodname = #{goodname,jdbcType=VARCHAR}");
        }
        
        if (record.getPhotoId() != null) {
            SET("photo_id = #{photoId,jdbcType=VARCHAR}");
        }
        
        if (record.getShowmoney() != null) {
            SET("showmoney = #{showmoney,jdbcType=REAL}");
        }
        
        if (record.getStat() != null) {
            SET("stat = #{stat,jdbcType=CHAR}");
        }
        
        if (record.getClassId() != null) {
            SET("class_id = #{classId,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}