package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdCProxyArea;

public class XxdCProxyAreaSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_proxy_area
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCProxyArea record) {
        BEGIN();
        INSERT_INTO("xxd_c_proxy_area");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getAreaid() != null) {
            VALUES("areaid", "#{areaid,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaname() != null) {
            VALUES("areaname", "#{areaname,jdbcType=VARCHAR}");
        }
        
        if (record.getAreatypeId() != null) {
            VALUES("areatype_id", "#{areatypeId,jdbcType=SMALLINT}");
        }
        
        if (record.getRemark() != null) {
            VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getLongitude() != null) {
            VALUES("longitude", "#{longitude,jdbcType=DECIMAL}");
        }
        
        if (record.getLatitude() != null) {
            VALUES("latitude", "#{latitude,jdbcType=DECIMAL}");
        }
        
        if (record.getProtocol() != null) {
            VALUES("protocol", "#{protocol,jdbcType=VARCHAR}");
        }
        
        if (record.getStat() != null) {
            VALUES("stat", "#{stat,jdbcType=CHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_proxy_area
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCProxyArea record) {
        BEGIN();
        UPDATE("xxd_c_proxy_area");
        
        if (record.getAreaid() != null) {
            SET("areaid = #{areaid,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaname() != null) {
            SET("areaname = #{areaname,jdbcType=VARCHAR}");
        }
        
        if (record.getAreatypeId() != null) {
            SET("areatype_id = #{areatypeId,jdbcType=SMALLINT}");
        }
        
        if (record.getRemark() != null) {
            SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getLongitude() != null) {
            SET("longitude = #{longitude,jdbcType=DECIMAL}");
        }
        
        if (record.getLatitude() != null) {
            SET("latitude = #{latitude,jdbcType=DECIMAL}");
        }
        
        if (record.getProtocol() != null) {
            SET("protocol = #{protocol,jdbcType=VARCHAR}");
        }
        
        if (record.getStat() != null) {
            SET("stat = #{stat,jdbcType=CHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}