package com.xxd.mappers;

import com.xxd.models.XxdCGoodPhotes;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdCGoodPhotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_good_photos
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_c_good_photos",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_good_photos
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_c_good_photos (id, phid, ",
        "album, remark, homePname)",
        "values (#{id,jdbcType=INTEGER}, #{phid,jdbcType=VARCHAR}, ",
        "#{album,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, #{homepname,jdbcType=VARCHAR})"
    })
    int insert(XxdCGoodPhotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_good_photos
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdCGoodPhotesSqlProvider.class, method="insertSelective")
    int insertSelective(XxdCGoodPhotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_good_photos
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, phid, album, remark, homePname",
        "from xxd_c_good_photos",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="phid", property="phid", jdbcType=JdbcType.VARCHAR),
        @Result(column="album", property="album", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="homePname", property="homepname", jdbcType=JdbcType.VARCHAR)
    })
    XxdCGoodPhotes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_good_photos
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdCGoodPhotesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdCGoodPhotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_good_photos
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_c_good_photos",
        "set phid = #{phid,jdbcType=VARCHAR},",
          "album = #{album,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "homePname = #{homepname,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdCGoodPhotes record);
}