package com.xxd.mappers;

import com.xxd.models.XxdCProxyAreaGood;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdCProxyAreaGoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_proxy_area_good
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_c_proxy_area_good",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_proxy_area_good
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_c_proxy_area_good (id, area_id, ",
        "good_id, commision)",
        "values (#{id,jdbcType=INTEGER}, #{areaId,jdbcType=VARCHAR}, ",
        "#{goodId,jdbcType=VARCHAR}, #{commision,jdbcType=REAL})"
    })
    int insert(XxdCProxyAreaGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_proxy_area_good
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdCProxyAreaGoodSqlProvider.class, method="insertSelective")
    int insertSelective(XxdCProxyAreaGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_proxy_area_good
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, area_id, good_id, commision",
        "from xxd_c_proxy_area_good",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.VARCHAR),
        @Result(column="good_id", property="goodId", jdbcType=JdbcType.VARCHAR),
        @Result(column="commision", property="commision", jdbcType=JdbcType.REAL)
    })
    XxdCProxyAreaGood selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_proxy_area_good
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdCProxyAreaGoodSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdCProxyAreaGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_proxy_area_good
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_c_proxy_area_good",
        "set area_id = #{areaId,jdbcType=VARCHAR},",
          "good_id = #{goodId,jdbcType=VARCHAR},",
          "commision = #{commision,jdbcType=REAL}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdCProxyAreaGood record);
}