package com.xxd.mappers;

import com.xxd.models.XxdCGroupArea;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdCGroupAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group_area
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_c_group_area",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group_area
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_c_group_area (id, group_id, ",
        "area_id, startdate, ",
        "enddate, stat, cause)",
        "values (#{id,jdbcType=INTEGER}, #{groupId,jdbcType=VARCHAR}, ",
        "#{areaId,jdbcType=VARCHAR}, #{startdate,jdbcType=TIMESTAMP}, ",
        "#{enddate,jdbcType=TIMESTAMP}, #{stat,jdbcType=CHAR}, #{cause,jdbcType=VARCHAR})"
    })
    int insert(XxdCGroupArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group_area
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdCGroupAreaSqlProvider.class, method="insertSelective")
    int insertSelective(XxdCGroupArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group_area
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, group_id, area_id, startdate, enddate, stat, cause",
        "from xxd_c_group_area",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="group_id", property="groupId", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.VARCHAR),
        @Result(column="startdate", property="startdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="enddate", property="enddate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="cause", property="cause", jdbcType=JdbcType.VARCHAR)
    })
    XxdCGroupArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group_area
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdCGroupAreaSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdCGroupArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_group_area
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_c_group_area",
        "set group_id = #{groupId,jdbcType=VARCHAR},",
          "area_id = #{areaId,jdbcType=VARCHAR},",
          "startdate = #{startdate,jdbcType=TIMESTAMP},",
          "enddate = #{enddate,jdbcType=TIMESTAMP},",
          "stat = #{stat,jdbcType=CHAR},",
          "cause = #{cause,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdCGroupArea record);
}