package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdCShopBusinessHours;

public class XxdCShopBusinessHoursSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_business_hours
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCShopBusinessHours record) {
        BEGIN();
        INSERT_INTO("xxd_c_shop_business_hours");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getMondayStarttime() != null) {
            VALUES("monday_starttime", "#{mondayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTuesdayStarttime() != null) {
            VALUES("tuesday_starttime", "#{tuesdayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWednesdayStarttime() != null) {
            VALUES("wednesday_starttime", "#{wednesdayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getThursdayStarttime() != null) {
            VALUES("thursday_starttime", "#{thursdayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFridayStarttime() != null) {
            VALUES("friday_starttime", "#{fridayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSaturdayStarttime() != null) {
            VALUES("saturday_starttime", "#{saturdayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSundayStarttime() != null) {
            VALUES("sunday_starttime", "#{sundayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getMondayEndtime() != null) {
            VALUES("monday_endtime", "#{mondayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTuesdayEndtime() != null) {
            VALUES("tuesday_endtime", "#{tuesdayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWednesdayEndtime() != null) {
            VALUES("wednesday_endtime", "#{wednesdayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getThursdayEndtime() != null) {
            VALUES("thursday_endtime", "#{thursdayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFridayEndtime() != null) {
            VALUES("friday_endtime", "#{fridayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSaturdayEndtime() != null) {
            VALUES("saturday_endtime", "#{saturdayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSundayEndtime() != null) {
            VALUES("sunday_endtime", "#{sundayEndtime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_business_hours
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCShopBusinessHours record) {
        BEGIN();
        UPDATE("xxd_c_shop_business_hours");
        
        if (record.getMondayStarttime() != null) {
            SET("monday_starttime = #{mondayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTuesdayStarttime() != null) {
            SET("tuesday_starttime = #{tuesdayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWednesdayStarttime() != null) {
            SET("wednesday_starttime = #{wednesdayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getThursdayStarttime() != null) {
            SET("thursday_starttime = #{thursdayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFridayStarttime() != null) {
            SET("friday_starttime = #{fridayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSaturdayStarttime() != null) {
            SET("saturday_starttime = #{saturdayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSundayStarttime() != null) {
            SET("sunday_starttime = #{sundayStarttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getMondayEndtime() != null) {
            SET("monday_endtime = #{mondayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTuesdayEndtime() != null) {
            SET("tuesday_endtime = #{tuesdayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWednesdayEndtime() != null) {
            SET("wednesday_endtime = #{wednesdayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getThursdayEndtime() != null) {
            SET("thursday_endtime = #{thursdayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFridayEndtime() != null) {
            SET("friday_endtime = #{fridayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSaturdayEndtime() != null) {
            SET("saturday_endtime = #{saturdayEndtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSundayEndtime() != null) {
            SET("sunday_endtime = #{sundayEndtime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}