package com.xxd.mappers;

import com.xxd.models.XxdCSpu;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdCSpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_c_spu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_c_spu (id, name, ",
        "parentid, childid, ",
        "iscolor, isenum, isinput, ",
        "isprimary, issale, stat, ",
        "sort_no)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{parentid,jdbcType=INTEGER}, #{childid,jdbcType=INTEGER}, ",
        "#{iscolor,jdbcType=CHAR}, #{isenum,jdbcType=CHAR}, #{isinput,jdbcType=CHAR}, ",
        "#{isprimary,jdbcType=CHAR}, #{issale,jdbcType=CHAR}, #{stat,jdbcType=CHAR}, ",
        "#{sortNo,jdbcType=SMALLINT})"
    })
    int insert(XxdCSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdCSpuSqlProvider.class, method="insertSelective")
    int insertSelective(XxdCSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, parentid, childid, iscolor, isenum, isinput, isprimary, issale, stat, ",
        "sort_no",
        "from xxd_c_spu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="parentid", property="parentid", jdbcType=JdbcType.INTEGER),
        @Result(column="childid", property="childid", jdbcType=JdbcType.INTEGER),
        @Result(column="iscolor", property="iscolor", jdbcType=JdbcType.CHAR),
        @Result(column="isenum", property="isenum", jdbcType=JdbcType.CHAR),
        @Result(column="isinput", property="isinput", jdbcType=JdbcType.CHAR),
        @Result(column="isprimary", property="isprimary", jdbcType=JdbcType.CHAR),
        @Result(column="issale", property="issale", jdbcType=JdbcType.CHAR),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="sort_no", property="sortNo", jdbcType=JdbcType.SMALLINT)
    })
    XxdCSpu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdCSpuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdCSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_c_spu",
        "set name = #{name,jdbcType=VARCHAR},",
          "parentid = #{parentid,jdbcType=INTEGER},",
          "childid = #{childid,jdbcType=INTEGER},",
          "iscolor = #{iscolor,jdbcType=CHAR},",
          "isenum = #{isenum,jdbcType=CHAR},",
          "isinput = #{isinput,jdbcType=CHAR},",
          "isprimary = #{isprimary,jdbcType=CHAR},",
          "issale = #{issale,jdbcType=CHAR},",
          "stat = #{stat,jdbcType=CHAR},",
          "sort_no = #{sortNo,jdbcType=SMALLINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdCSpu record);
}