package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdCPhotos;

public class XxdCPhotosSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_photos
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCPhotos record) {
        BEGIN();
        INSERT_INTO("xxd_c_photos");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getPid() != null) {
            VALUES("pid", "#{pid,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodPhId() != null) {
            VALUES("good_ph_id", "#{goodPhId,jdbcType=VARCHAR}");
        }
        
        if (record.getCommId() != null) {
            VALUES("comm_id", "#{commId,jdbcType=VARCHAR}");
        }
        
        if (record.getAlbum() != null) {
            VALUES("album", "#{album,jdbcType=VARCHAR}");
        }
        
        if (record.getHrefaddr() != null) {
            VALUES("hrefaddr", "#{hrefaddr,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            VALUES("type", "#{type,jdbcType=CHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_photos
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCPhotos record) {
        BEGIN();
        UPDATE("xxd_c_photos");
        
        if (record.getPid() != null) {
            SET("pid = #{pid,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodPhId() != null) {
            SET("good_ph_id = #{goodPhId,jdbcType=VARCHAR}");
        }
        
        if (record.getCommId() != null) {
            SET("comm_id = #{commId,jdbcType=VARCHAR}");
        }
        
        if (record.getAlbum() != null) {
            SET("album = #{album,jdbcType=VARCHAR}");
        }
        
        if (record.getHrefaddr() != null) {
            SET("hrefaddr = #{hrefaddr,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            SET("type = #{type,jdbcType=CHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}