package com.xxd.mappers;

import com.xxd.models.XxdCShopArea;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdCShopAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_area
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_c_shop_area",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_area
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_c_shop_area (id, shop_id, ",
        "area_id, stat)",
        "values (#{id,jdbcType=INTEGER}, #{shopId,jdbcType=VARCHAR}, ",
        "#{areaId,jdbcType=VARCHAR}, #{stat,jdbcType=CHAR})"
    })
    int insert(XxdCShopArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_area
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdCShopAreaSqlProvider.class, method="insertSelective")
    int insertSelective(XxdCShopArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_area
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, shop_id, area_id, stat",
        "from xxd_c_shop_area",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="shop_id", property="shopId", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.VARCHAR),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR)
    })
    XxdCShopArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_area
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdCShopAreaSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdCShopArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_area
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_c_shop_area",
        "set shop_id = #{shopId,jdbcType=VARCHAR},",
          "area_id = #{areaId,jdbcType=VARCHAR},",
          "stat = #{stat,jdbcType=CHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdCShopArea record);
}