package com.xxd.mappers;

import com.xxd.models.XxdCShop;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdCShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_c_shop",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_c_shop (id, sid, ",
        "shopname, address, ",
        "addressDetail, longitude, ",
        "latitude, category_id, ",
        "phone, notice, stat, ",
        "service_id, business_hours_id, ",
        "scale, reservenotes)",
        "values (#{id,jdbcType=INTEGER}, #{sid,jdbcType=VARCHAR}, ",
        "#{shopname,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{addressdetail,jdbcType=VARCHAR}, #{longitude,jdbcType=VARCHAR}, ",
        "#{latitude,jdbcType=VARCHAR}, #{categoryId,jdbcType=INTEGER}, ",
        "#{phone,jdbcType=VARCHAR}, #{notice,jdbcType=VARCHAR}, #{stat,jdbcType=CHAR}, ",
        "#{serviceId,jdbcType=SMALLINT}, #{businessHoursId,jdbcType=SMALLINT}, ",
        "#{scale,jdbcType=VARCHAR}, #{reservenotes,jdbcType=VARCHAR})"
    })
    int insert(XxdCShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdCShopSqlProvider.class, method="insertSelective")
    int insertSelective(XxdCShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, sid, shopname, address, addressDetail, longitude, latitude, category_id, ",
        "phone, notice, stat, service_id, business_hours_id, scale, reservenotes",
        "from xxd_c_shop",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="sid", property="sid", jdbcType=JdbcType.VARCHAR),
        @Result(column="shopname", property="shopname", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="addressDetail", property="addressdetail", jdbcType=JdbcType.VARCHAR),
        @Result(column="longitude", property="longitude", jdbcType=JdbcType.VARCHAR),
        @Result(column="latitude", property="latitude", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="notice", property="notice", jdbcType=JdbcType.VARCHAR),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="service_id", property="serviceId", jdbcType=JdbcType.SMALLINT),
        @Result(column="business_hours_id", property="businessHoursId", jdbcType=JdbcType.SMALLINT),
        @Result(column="scale", property="scale", jdbcType=JdbcType.VARCHAR),
        @Result(column="reservenotes", property="reservenotes", jdbcType=JdbcType.VARCHAR)
    })
    XxdCShop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdCShopSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdCShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_c_shop",
        "set sid = #{sid,jdbcType=VARCHAR},",
          "shopname = #{shopname,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "addressDetail = #{addressdetail,jdbcType=VARCHAR},",
          "longitude = #{longitude,jdbcType=VARCHAR},",
          "latitude = #{latitude,jdbcType=VARCHAR},",
          "category_id = #{categoryId,jdbcType=INTEGER},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "notice = #{notice,jdbcType=VARCHAR},",
          "stat = #{stat,jdbcType=CHAR},",
          "service_id = #{serviceId,jdbcType=SMALLINT},",
          "business_hours_id = #{businessHoursId,jdbcType=SMALLINT},",
          "scale = #{scale,jdbcType=VARCHAR},",
          "reservenotes = #{reservenotes,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdCShop record);
}