package com.xxd.mappers;

import com.xxd.models.XxdCGoodsSkuSpuValue;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdCGoodsSkuSpuValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods_sku_spu_value
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_c_goods_sku_spu_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods_sku_spu_value
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_c_goods_sku_spu_value (id, sku_id, ",
        "spu_value_id, stat)",
        "values (#{id,jdbcType=INTEGER}, #{skuId,jdbcType=INTEGER}, ",
        "#{spuValueId,jdbcType=INTEGER}, #{stat,jdbcType=CHAR})"
    })
    int insert(XxdCGoodsSkuSpuValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods_sku_spu_value
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdCGoodsSkuSpuValueSqlProvider.class, method="insertSelective")
    int insertSelective(XxdCGoodsSkuSpuValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods_sku_spu_value
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, sku_id, spu_value_id, stat",
        "from xxd_c_goods_sku_spu_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.INTEGER),
        @Result(column="spu_value_id", property="spuValueId", jdbcType=JdbcType.INTEGER),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR)
    })
    XxdCGoodsSkuSpuValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods_sku_spu_value
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdCGoodsSkuSpuValueSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdCGoodsSkuSpuValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods_sku_spu_value
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_c_goods_sku_spu_value",
        "set sku_id = #{skuId,jdbcType=INTEGER},",
          "spu_value_id = #{spuValueId,jdbcType=INTEGER},",
          "stat = #{stat,jdbcType=CHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdCGoodsSkuSpuValue record);
}