package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdCShop;

public class XxdCShopSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCShop record) {
        BEGIN();
        INSERT_INTO("xxd_c_shop");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getSid() != null) {
            VALUES("sid", "#{sid,jdbcType=VARCHAR}");
        }
        
        if (record.getShopname() != null) {
            VALUES("shopname", "#{shopname,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            VALUES("address", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getAddressdetail() != null) {
            VALUES("addressDetail", "#{addressdetail,jdbcType=VARCHAR}");
        }
        
        if (record.getLongitude() != null) {
            VALUES("longitude", "#{longitude,jdbcType=VARCHAR}");
        }
        
        if (record.getLatitude() != null) {
            VALUES("latitude", "#{latitude,jdbcType=VARCHAR}");
        }
        
        if (record.getCategoryId() != null) {
            VALUES("category_id", "#{categoryId,jdbcType=INTEGER}");
        }
        
        if (record.getPhone() != null) {
            VALUES("phone", "#{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getNotice() != null) {
            VALUES("notice", "#{notice,jdbcType=VARCHAR}");
        }
        
        if (record.getStat() != null) {
            VALUES("stat", "#{stat,jdbcType=CHAR}");
        }
        
        if (record.getServiceId() != null) {
            VALUES("service_id", "#{serviceId,jdbcType=SMALLINT}");
        }
        
        if (record.getBusinessHoursId() != null) {
            VALUES("business_hours_id", "#{businessHoursId,jdbcType=SMALLINT}");
        }
        
        if (record.getScale() != null) {
            VALUES("scale", "#{scale,jdbcType=VARCHAR}");
        }
        
        if (record.getReservenotes() != null) {
            VALUES("reservenotes", "#{reservenotes,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCShop record) {
        BEGIN();
        UPDATE("xxd_c_shop");
        
        if (record.getSid() != null) {
            SET("sid = #{sid,jdbcType=VARCHAR}");
        }
        
        if (record.getShopname() != null) {
            SET("shopname = #{shopname,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            SET("address = #{address,jdbcType=VARCHAR}");
        }
        
        if (record.getAddressdetail() != null) {
            SET("addressDetail = #{addressdetail,jdbcType=VARCHAR}");
        }
        
        if (record.getLongitude() != null) {
            SET("longitude = #{longitude,jdbcType=VARCHAR}");
        }
        
        if (record.getLatitude() != null) {
            SET("latitude = #{latitude,jdbcType=VARCHAR}");
        }
        
        if (record.getCategoryId() != null) {
            SET("category_id = #{categoryId,jdbcType=INTEGER}");
        }
        
        if (record.getPhone() != null) {
            SET("phone = #{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getNotice() != null) {
            SET("notice = #{notice,jdbcType=VARCHAR}");
        }
        
        if (record.getStat() != null) {
            SET("stat = #{stat,jdbcType=CHAR}");
        }
        
        if (record.getServiceId() != null) {
            SET("service_id = #{serviceId,jdbcType=SMALLINT}");
        }
        
        if (record.getBusinessHoursId() != null) {
            SET("business_hours_id = #{businessHoursId,jdbcType=SMALLINT}");
        }
        
        if (record.getScale() != null) {
            SET("scale = #{scale,jdbcType=VARCHAR}");
        }
        
        if (record.getReservenotes() != null) {
            SET("reservenotes = #{reservenotes,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}