package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdCShopArea;

public class XxdCShopAreaSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_area
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCShopArea record) {
        BEGIN();
        INSERT_INTO("xxd_c_shop_area");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getShopId() != null) {
            VALUES("shop_id", "#{shopId,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaId() != null) {
            VALUES("area_id", "#{areaId,jdbcType=VARCHAR}");
        }
        
        if (record.getStat() != null) {
            VALUES("stat", "#{stat,jdbcType=CHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_area
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCShopArea record) {
        BEGIN();
        UPDATE("xxd_c_shop_area");
        
        if (record.getShopId() != null) {
            SET("shop_id = #{shopId,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaId() != null) {
            SET("area_id = #{areaId,jdbcType=VARCHAR}");
        }
        
        if (record.getStat() != null) {
            SET("stat = #{stat,jdbcType=CHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}