package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdCGoodsSkuSpuValue;

public class XxdCGoodsSkuSpuValueSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods_sku_spu_value
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCGoodsSkuSpuValue record) {
        BEGIN();
        INSERT_INTO("xxd_c_goods_sku_spu_value");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getSkuId() != null) {
            VALUES("sku_id", "#{skuId,jdbcType=INTEGER}");
        }
        
        if (record.getSpuValueId() != null) {
            VALUES("spu_value_id", "#{spuValueId,jdbcType=INTEGER}");
        }
        
        if (record.getStat() != null) {
            VALUES("stat", "#{stat,jdbcType=CHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_goods_sku_spu_value
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCGoodsSkuSpuValue record) {
        BEGIN();
        UPDATE("xxd_c_goods_sku_spu_value");
        
        if (record.getSkuId() != null) {
            SET("sku_id = #{skuId,jdbcType=INTEGER}");
        }
        
        if (record.getSpuValueId() != null) {
            SET("spu_value_id = #{spuValueId,jdbcType=INTEGER}");
        }
        
        if (record.getStat() != null) {
            SET("stat = #{stat,jdbcType=CHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}