package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdCGoodPhotes;

public class XxdCGoodPhotesSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_good_photos
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCGoodPhotes record) {
        BEGIN();
        INSERT_INTO("xxd_c_good_photos");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getPhid() != null) {
            VALUES("phid", "#{phid,jdbcType=VARCHAR}");
        }
        
        if (record.getAlbum() != null) {
            VALUES("album", "#{album,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getHomepname() != null) {
            VALUES("homePname", "#{homepname,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_good_photos
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCGoodPhotes record) {
        BEGIN();
        UPDATE("xxd_c_good_photos");
        
        if (record.getPhid() != null) {
            SET("phid = #{phid,jdbcType=VARCHAR}");
        }
        
        if (record.getAlbum() != null) {
            SET("album = #{album,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getHomepname() != null) {
            SET("homePname = #{homepname,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}