package com.xxd.mappers;

import com.xxd.models.XxdCShopBusinessHours;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdCShopBusinessHoursMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_business_hours
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_c_shop_business_hours",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_business_hours
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_c_shop_business_hours (id, monday_starttime, ",
        "tuesday_starttime, wednesday_starttime, ",
        "thursday_starttime, friday_starttime, ",
        "saturday_starttime, sunday_starttime, ",
        "monday_endtime, tuesday_endtime, ",
        "wednesday_endtime, thursday_endtime, ",
        "friday_endtime, saturday_endtime, ",
        "sunday_endtime)",
        "values (#{id,jdbcType=INTEGER}, #{mondayStarttime,jdbcType=TIMESTAMP}, ",
        "#{tuesdayStarttime,jdbcType=TIMESTAMP}, #{wednesdayStarttime,jdbcType=TIMESTAMP}, ",
        "#{thursdayStarttime,jdbcType=TIMESTAMP}, #{fridayStarttime,jdbcType=TIMESTAMP}, ",
        "#{saturdayStarttime,jdbcType=TIMESTAMP}, #{sundayStarttime,jdbcType=TIMESTAMP}, ",
        "#{mondayEndtime,jdbcType=TIMESTAMP}, #{tuesdayEndtime,jdbcType=TIMESTAMP}, ",
        "#{wednesdayEndtime,jdbcType=TIMESTAMP}, #{thursdayEndtime,jdbcType=TIMESTAMP}, ",
        "#{fridayEndtime,jdbcType=TIMESTAMP}, #{saturdayEndtime,jdbcType=TIMESTAMP}, ",
        "#{sundayEndtime,jdbcType=TIMESTAMP})"
    })
    int insert(XxdCShopBusinessHours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_business_hours
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdCShopBusinessHoursSqlProvider.class, method="insertSelective")
    int insertSelective(XxdCShopBusinessHours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_business_hours
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, monday_starttime, tuesday_starttime, wednesday_starttime, thursday_starttime, ",
        "friday_starttime, saturday_starttime, sunday_starttime, monday_endtime, tuesday_endtime, ",
        "wednesday_endtime, thursday_endtime, friday_endtime, saturday_endtime, sunday_endtime",
        "from xxd_c_shop_business_hours",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="monday_starttime", property="mondayStarttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="tuesday_starttime", property="tuesdayStarttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="wednesday_starttime", property="wednesdayStarttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thursday_starttime", property="thursdayStarttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="friday_starttime", property="fridayStarttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="saturday_starttime", property="saturdayStarttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="sunday_starttime", property="sundayStarttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="monday_endtime", property="mondayEndtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="tuesday_endtime", property="tuesdayEndtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="wednesday_endtime", property="wednesdayEndtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thursday_endtime", property="thursdayEndtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="friday_endtime", property="fridayEndtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="saturday_endtime", property="saturdayEndtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="sunday_endtime", property="sundayEndtime", jdbcType=JdbcType.TIMESTAMP)
    })
    XxdCShopBusinessHours selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_business_hours
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdCShopBusinessHoursSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdCShopBusinessHours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_shop_business_hours
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_c_shop_business_hours",
        "set monday_starttime = #{mondayStarttime,jdbcType=TIMESTAMP},",
          "tuesday_starttime = #{tuesdayStarttime,jdbcType=TIMESTAMP},",
          "wednesday_starttime = #{wednesdayStarttime,jdbcType=TIMESTAMP},",
          "thursday_starttime = #{thursdayStarttime,jdbcType=TIMESTAMP},",
          "friday_starttime = #{fridayStarttime,jdbcType=TIMESTAMP},",
          "saturday_starttime = #{saturdayStarttime,jdbcType=TIMESTAMP},",
          "sunday_starttime = #{sundayStarttime,jdbcType=TIMESTAMP},",
          "monday_endtime = #{mondayEndtime,jdbcType=TIMESTAMP},",
          "tuesday_endtime = #{tuesdayEndtime,jdbcType=TIMESTAMP},",
          "wednesday_endtime = #{wednesdayEndtime,jdbcType=TIMESTAMP},",
          "thursday_endtime = #{thursdayEndtime,jdbcType=TIMESTAMP},",
          "friday_endtime = #{fridayEndtime,jdbcType=TIMESTAMP},",
          "saturday_endtime = #{saturdayEndtime,jdbcType=TIMESTAMP},",
          "sunday_endtime = #{sundayEndtime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdCShopBusinessHours record);
}