package com.xxd.mappers;

import com.xxd.models.XxdCSpuValue;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdCSpuValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu_value
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_c_spu_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu_value
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_c_spu_value (id, spu_id, ",
        "val, stat, sort_no)",
        "values (#{id,jdbcType=INTEGER}, #{spuId,jdbcType=INTEGER}, ",
        "#{val,jdbcType=VARCHAR}, #{stat,jdbcType=CHAR}, #{sortNo,jdbcType=SMALLINT})"
    })
    int insert(XxdCSpuValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu_value
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdCSpuValueSqlProvider.class, method="insertSelective")
    int insertSelective(XxdCSpuValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu_value
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, spu_id, val, stat, sort_no",
        "from xxd_c_spu_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="val", property="val", jdbcType=JdbcType.VARCHAR),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="sort_no", property="sortNo", jdbcType=JdbcType.SMALLINT)
    })
    XxdCSpuValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu_value
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdCSpuValueSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdCSpuValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_c_spu_value
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_c_spu_value",
        "set spu_id = #{spuId,jdbcType=INTEGER},",
          "val = #{val,jdbcType=VARCHAR},",
          "stat = #{stat,jdbcType=CHAR},",
          "sort_no = #{sortNo,jdbcType=SMALLINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdCSpuValue record);
}