package com.xxd.mappers;

import com.xxd.models.XxdGoodsPriceFlash;
import com.xxd.models.XxdGoodsPriceFlashBak;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdGoodsPriceFlashBakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_flash_bak
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_goods_price_flash_bak",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_flash_bak
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_goods_price_flash_bak (id, goods_flash_bak_id, goods_price_stock, format_name, market_price, member_price, flash_member_price, img, price, goods_price_stock_bak)",
        "values (#{id,jdbcType=INTEGER}, #{goodsFlashBakId,jdbcType=INTEGER}, ",
        "#{goodsPriceStock,jdbcType=INTEGER}, #{formatName,jdbcType=VARCHAR}, ",
        "#{marketPrice,jdbcType=DECIMAL}, #{memberPrice,jdbcType=DECIMAL}, ",
        "#{flashMemberPrice,jdbcType=DECIMAL}, #{img,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{goodsPriceStockBak,jdbcType=INTEGER})"
    })
    int insert(XxdGoodsPriceFlashBak record);
    
    @Insert({
        "insert into xxd_goods_price_flash_bak (id, goods_flash_bak_id, goods_price_stock, format_name, market_price, member_price, flash_member_price, img, price, goods_price_stock_bak)",
        "values (#{id,jdbcType=INTEGER}, #{goodsFlashBakId,jdbcType=INTEGER}, ",
        "#{goodsPriceStock,jdbcType=INTEGER}, #{formatName,jdbcType=VARCHAR}, ",
        "#{marketPrice,jdbcType=DECIMAL}, #{memberPrice,jdbcType=DECIMAL}, ",
        "#{flashMemberPrice,jdbcType=DECIMAL}, #{img,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{goodsPriceStockBak,jdbcType=INTEGER})"
    })
    int insertGoodsPriceFlash(XxdGoodsPriceFlash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_flash_bak
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdGoodsPriceFlashBakSqlProvider.class, method="insertSelective")
    int insertSelective(XxdGoodsPriceFlashBak record);
    
    @Insert({
        "insert into",
        "xxd_goods_price_flash_bak(id, goods_flash_bak_id, goods_price_stock, format_name, market_price, member_price, flash_member_price, img, price, goods_price_stock_bak)",
        "select xggf.id, xggf.goods_flash_id, xggf.goods_price_stock, xggf.format_name, xggf.market_price, xggf.member_price, xggf.flash_member_price, xggf.img, xggf.price, xggf.goods_price_stock_bak",
        "from xxd_goods_flash xgf inner join xxd_goods_price_flash xggf on xgf.id = xggf.goods_flash_id",
        "where xgf.end_time = #{end_time,jdbcType=VARCHAR}"
    })
    int insertFromOverFlashPrice(String end_time);
    
    @Delete({
        "delete from xxd_goods_price_flash where goods_flash_id in (",
        "select id",
        "from xxd_goods_flash",
        "where end_time = #{end_time,jdbcType=VARCHAR})"
    })
    int deleteFromOverGroupPrice(String end_time);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_flash_bak
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, goods_flash_bak_id, goods_price_stock, format_name, market_price, member_price, ",
        "flash_member_price, img, price, goods_price_stock_bak",
        "from xxd_goods_price_flash_bak",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goods_flash_bak_id", property="goodsFlashBakId", jdbcType=JdbcType.INTEGER),
        @Result(column="goods_price_stock", property="goodsPriceStock", jdbcType=JdbcType.INTEGER),
        @Result(column="format_name", property="formatName", jdbcType=JdbcType.VARCHAR),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="member_price", property="memberPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="flash_member_price", property="flashMemberPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_price_stock_bak", property="goodsPriceStockBak", jdbcType=JdbcType.INTEGER)
    })
    XxdGoodsPriceFlashBak selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_flash_bak
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdGoodsPriceFlashBakSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdGoodsPriceFlashBak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_flash_bak
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_goods_price_flash_bak",
        "set goods_flash_bak_id = #{goodsFlashBakId,jdbcType=INTEGER},",
          "goods_price_stock = #{goodsPriceStock,jdbcType=INTEGER},",
          "format_name = #{formatName,jdbcType=VARCHAR},",
          "market_price = #{marketPrice,jdbcType=DECIMAL},",
          "member_price = #{memberPrice,jdbcType=DECIMAL},",
          "flash_member_price = #{flashMemberPrice,jdbcType=DECIMAL},",
          "img = #{img,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "goods_price_stock_bak = #{goodsPriceStockBak,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdGoodsPriceFlashBak record);
}