package com.xxd.mappers;

import com.xxd.models.XxdGoodsPriceGroup;
import com.xxd.models.XxdGoodsPriceGroupBak;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdGoodsPriceGroupBakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_group_bak
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_goods_price_group_bak",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_group_bak
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_goods_price_group_bak (id, goods_group_bak_id, ",
        "goods_price_stock, format_name, ",
        "market_price, member_price, ",
        "group_member_price, img, ",
        "price, goods_price_stock_bak)",
        "values (#{id,jdbcType=INTEGER}, #{goodsGroupBakId,jdbcType=INTEGER}, ",
        "#{goodsPriceStock,jdbcType=INTEGER}, #{formatName,jdbcType=VARCHAR}, ",
        "#{marketPrice,jdbcType=DECIMAL}, #{memberPrice,jdbcType=DECIMAL}, ",
        "#{groupMemberPrice,jdbcType=DECIMAL}, #{img,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{goodsPriceStockBak,jdbcType=INTEGER})"
    })
    int insert(XxdGoodsPriceGroupBak record);
    
    @Insert({
        "insert into xxd_goods_price_group_bak (id, goods_group_bak_id, ",
        "goods_price_stock, format_name, ",
        "market_price, member_price, ",
        "group_member_price, img, ",
        "price, goods_price_stock_bak)",
        "values (#{id,jdbcType=INTEGER}, #{goodsGroupBakId,jdbcType=INTEGER}, ",
        "#{goodsPriceStock,jdbcType=INTEGER}, #{formatName,jdbcType=VARCHAR}, ",
        "#{marketPrice,jdbcType=DECIMAL}, #{memberPrice,jdbcType=DECIMAL}, ",
        "#{groupMemberPrice,jdbcType=DECIMAL}, #{img,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{goodsPriceStockBak,jdbcType=INTEGER})"
    })
    int insertGoodsPriceGroup(XxdGoodsPriceGroup record);
    
    @Insert({
        "insert into",
        "xxd_goods_price_group_bak(id, goods_group_bak_id, goods_price_stock, format_name, market_price, member_price, group_member_price, img, price, goods_price_stock_bak)",
        "select xggp.id, xggp.goods_group_id, xggp.goods_price_stock, xggp.format_name, xggp.market_price, xggp.member_price, xggp.group_member_price, xggp.img, xggp.price, xggp.goods_price_stock_bak",
        "from xxd_goods_group xgg inner join xxd_goods_price_group xggp on xgg.id = xggp.goods_group_id",
        "where xgg.group_end_time = date_format(now(), '%Y-%m-%d 22:00:00')"
    })
    int insertFromOverGroupPrice();
    
    @Delete({
        "delete from xxd_goods_price_group where goods_group_id in (select id from xxd_goods_group where group_end_time = date_format(now(), '%Y-%m-%d 22:00:00'))"
    })
    int deleteFromOverGroupPrice();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_group_bak
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdGoodsPriceGroupBakSqlProvider.class, method="insertSelective")
    int insertSelective(XxdGoodsPriceGroupBak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_group_bak
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, goods_group_bak_id, goods_price_stock, format_name, market_price, member_price, ",
        "group_member_price, img, price, goods_price_stock_bak",
        "from xxd_goods_price_group_bak",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goods_group_bak_id", property="goodsGroupBakId", jdbcType=JdbcType.INTEGER),
        @Result(column="goods_price_stock", property="goodsPriceStock", jdbcType=JdbcType.INTEGER),
        @Result(column="format_name", property="formatName", jdbcType=JdbcType.VARCHAR),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="member_price", property="memberPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="group_member_price", property="groupMemberPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_price_stock_bak", property="goodsPriceStockBak", jdbcType=JdbcType.INTEGER)
    })
    XxdGoodsPriceGroupBak selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_group_bak
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdGoodsPriceGroupBakSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdGoodsPriceGroupBak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price_group_bak
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_goods_price_group_bak",
        "set goods_group_bak_id = #{goodsGroupBakId,jdbcType=INTEGER},",
          "goods_price_stock = #{goodsPriceStock,jdbcType=INTEGER},",
          "format_name = #{formatName,jdbcType=VARCHAR},",
          "market_price = #{marketPrice,jdbcType=DECIMAL},",
          "member_price = #{memberPrice,jdbcType=DECIMAL},",
          "group_member_price = #{groupMemberPrice,jdbcType=DECIMAL},",
          "img = #{img,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "goods_price_stock_bak = #{goodsPriceStockBak,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdGoodsPriceGroupBak record);
}