package com.xxd.mappers;

import com.xxd.models.XxdBuyOrderDetails;
import com.xxd.models.XxdGoodsFlash;
import com.xxd.models.XxdGoodsFlashSta;

import java.util.ArrayList;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdGoodsFlashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_flash
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_goods_flash",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_flash
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_goods_flash (id, goods_id, ",
        "sta, start_time, ",
        "end_time, time, flash_title, ",
        "flash_picture)",
        "values (#{id,jdbcType=INTEGER}, #{goodsId,jdbcType=INTEGER}, ",
        "#{sta,jdbcType=SMALLINT}, #{startTime,jdbcType=VARCHAR}, ",
        "#{endTime,jdbcType=VARCHAR}, #{time,jdbcType=VARCHAR}, #{flashTitle,jdbcType=VARCHAR}, ",
        "#{flashPicture,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true, keyProperty="id", keyColumn="id")
    int insert(XxdGoodsFlash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_flash
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdGoodsFlashSqlProvider.class, method="insertSelective")
    int insertSelective(XxdGoodsFlash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_flash
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, goods_id, sta, start_time, end_time, time, flash_title, flash_picture",
        "from xxd_goods_flash",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.INTEGER),
        @Result(column="sta", property="sta", jdbcType=JdbcType.SMALLINT),
        @Result(column="start_time", property="startTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.VARCHAR),
        @Result(column="flash_title", property="flashTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="flash_picture", property="flashPicture", jdbcType=JdbcType.VARCHAR)
    })
    XxdGoodsFlash selectByPrimaryKey(Integer id);
    
    @Select({
        "select xbod.id id,xbo.id buy_order_id,xbod.prices prices,xbod.num num from",
        "(xxd_buy_order xbo inner join xxd_buy_order_details xbod on xbo.id = xbod.buy_order_id)",
        "inner join xxd_goods_flash xgf on xgf.goods_id = xbod.goods_id", 
        "where xbod.type = 4 and xgf.end_time = #{end_time,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="buy_order_id", property="buyOrderId", jdbcType=JdbcType.INTEGER),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="prices", property="prices", jdbcType=JdbcType.DECIMAL)
    })
    ArrayList<XxdBuyOrderDetails> selectInvaildOrder(String time);
    
    @Update({
    	"update xxd_goods set grounding_sta = #{grounding_sta,jdbcType=SMALLINT}",
        "where id in (select goods_id from xxd_goods_flash where start_time = #{start_time,jdbcType=VARCHAR})"
    })
    int updateFlashStaByStartTime(XxdGoodsFlashSta goodsFlashSta);
    
    @Update({
    	"update xxd_goods set grounding_sta = #{grounding_sta,jdbcType=SMALLINT}",
        "where id in (select goods_id from xxd_goods_flash where end_time = #{end_time,jdbcType=VARCHAR})"
    })
    int updateFlashStaByEndTime(XxdGoodsFlashSta goodsFlashSta);
    
    @Select({
        "select",
        "id, goods_id, sta, start_time, end_time, time, flash_title, flash_picture",
        "from xxd_goods_flash",
        "where goods_id = #{goodsId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.INTEGER),
        @Result(column="sta", property="sta", jdbcType=JdbcType.SMALLINT),
        @Result(column="start_time", property="startTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.VARCHAR),
        @Result(column="flash_title", property="flashTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="flash_picture", property="flashPicture", jdbcType=JdbcType.VARCHAR)
    })
    XxdGoodsFlash selectByGoodsId(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_flash
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdGoodsFlashSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdGoodsFlash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_flash
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_goods_flash",
        "set goods_id = #{goodsId,jdbcType=INTEGER},",
          "sta = #{sta,jdbcType=SMALLINT},",
          "start_time = #{startTime,jdbcType=VARCHAR},",
          "end_time = #{endTime,jdbcType=VARCHAR},",
          "time = #{time,jdbcType=VARCHAR},",
          "flash_title = #{flashTitle,jdbcType=VARCHAR},",
          "flash_picture = #{flashPicture,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdGoodsFlash record);
}