package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdGoodsFlash;
import com.xxd.models.XxdGoodsFlashBak;

public class XxdGoodsFlashBakSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_flash_bak
     *
     * @mbggenerated
     */
    public String insertSelective(XxdGoodsFlashBak record) {
        BEGIN();
        INSERT_INTO("xxd_goods_flash_bak");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsId() != null) {
            VALUES("goods_id", "#{goodsId,jdbcType=INTEGER}");
        }
        
        if (record.getSta() != null) {
            VALUES("sta", "#{sta,jdbcType=SMALLINT}");
        }
        
        if (record.getStartTime() != null) {
            VALUES("start_time", "#{startTime,jdbcType=VARCHAR}");
        }
        
        if (record.getEndTime() != null) {
            VALUES("end_time", "#{endTime,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            VALUES("time", "#{time,jdbcType=VARCHAR}");
        }
        
        if (record.getFlashTitle() != null) {
            VALUES("flash_title", "#{flashTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getFlashPicture() != null) {
            VALUES("flash_picture", "#{flashPicture,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_flash_bak
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdGoodsFlashBak record) {
        BEGIN();
        UPDATE("xxd_goods_flash_bak");
        
        if (record.getGoodsId() != null) {
            SET("goods_id = #{goodsId,jdbcType=INTEGER}");
        }
        
        if (record.getSta() != null) {
            SET("sta = #{sta,jdbcType=SMALLINT}");
        }
        
        if (record.getStartTime() != null) {
            SET("start_time = #{startTime,jdbcType=VARCHAR}");
        }
        
        if (record.getEndTime() != null) {
            SET("end_time = #{endTime,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            SET("time = #{time,jdbcType=VARCHAR}");
        }
        
        if (record.getFlashTitle() != null) {
            SET("flash_title = #{flashTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getFlashPicture() != null) {
            SET("flash_picture = #{flashPicture,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}