package com.xxd.mappers;

import com.xxd.models.XxdSystemNotification;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdSystemNotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_system_notification
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_system_notification",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_system_notification
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_system_notification (id, title, ",
        "type, pushTime, ",
        "user_group, content)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=SMALLINT}, #{pushtime,jdbcType=VARCHAR}, ",
        "#{userGroup,jdbcType=SMALLINT}, #{content,jdbcType=LONGVARCHAR})"
    })
    int insert(XxdSystemNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_system_notification
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdSystemNotificationSqlProvider.class, method="insertSelective")
    int insertSelective(XxdSystemNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_system_notification
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, title, type, pushTime, user_group, content",
        "from xxd_system_notification",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.SMALLINT),
        @Result(column="pushTime", property="pushtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_group", property="userGroup", jdbcType=JdbcType.SMALLINT),
        @Result(column="content", property="content", jdbcType=JdbcType.LONGVARCHAR)
    })
    XxdSystemNotification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_system_notification
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdSystemNotificationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdSystemNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_system_notification
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_system_notification",
        "set title = #{title,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=SMALLINT},",
          "pushTime = #{pushtime,jdbcType=VARCHAR},",
          "user_group = #{userGroup,jdbcType=SMALLINT},",
          "content = #{content,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(XxdSystemNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_system_notification
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_system_notification",
        "set title = #{title,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=SMALLINT},",
          "pushTime = #{pushtime,jdbcType=VARCHAR},",
          "user_group = #{userGroup,jdbcType=SMALLINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdSystemNotification record);
}