package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdSystemNotification;

public class XxdSystemNotificationSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_system_notification
     *
     * @mbggenerated
     */
    public String insertSelective(XxdSystemNotification record) {
        BEGIN();
        INSERT_INTO("xxd_system_notification");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            VALUES("type", "#{type,jdbcType=SMALLINT}");
        }
        
        if (record.getPushtime() != null) {
            VALUES("pushTime", "#{pushtime,jdbcType=VARCHAR}");
        }
        
        if (record.getUserGroup() != null) {
            VALUES("user_group", "#{userGroup,jdbcType=SMALLINT}");
        }
        
        if (record.getContent() != null) {
            VALUES("content", "#{content,jdbcType=LONGVARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_system_notification
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdSystemNotification record) {
        BEGIN();
        UPDATE("xxd_system_notification");
        
        if (record.getTitle() != null) {
            SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            SET("type = #{type,jdbcType=SMALLINT}");
        }
        
        if (record.getPushtime() != null) {
            SET("pushTime = #{pushtime,jdbcType=VARCHAR}");
        }
        
        if (record.getUserGroup() != null) {
            SET("user_group = #{userGroup,jdbcType=SMALLINT}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{content,jdbcType=LONGVARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}