package com.xxd.models;

public class XxdCGoodsSku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods_sku.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods_sku.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods_sku.good_id
     *
     * @mbggenerated
     */
    private String goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods_sku.money
     *
     * @mbggenerated
     */
    private Float money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods_sku.id
     *
     * @return the value of xxd_c_goods_sku.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods_sku.id
     *
     * @param id the value for xxd_c_goods_sku.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods_sku.num
     *
     * @return the value of xxd_c_goods_sku.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods_sku.num
     *
     * @param num the value for xxd_c_goods_sku.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods_sku.good_id
     *
     * @return the value of xxd_c_goods_sku.good_id
     *
     * @mbggenerated
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods_sku.good_id
     *
     * @param goodId the value for xxd_c_goods_sku.good_id
     *
     * @mbggenerated
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods_sku.money
     *
     * @return the value of xxd_c_goods_sku.money
     *
     * @mbggenerated
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods_sku.money
     *
     * @param money the value for xxd_c_goods_sku.money
     *
     * @mbggenerated
     */
    public void setMoney(Float money) {
        this.money = money;
    }
}