package com.xxd.models;

public class XxdCGoodsSkuSpuValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods_sku_spu_value.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods_sku_spu_value.sku_id
     *
     * @mbggenerated
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods_sku_spu_value.spu_value_id
     *
     * @mbggenerated
     */
    private Integer spuValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods_sku_spu_value.stat
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods_sku_spu_value.id
     *
     * @return the value of xxd_c_goods_sku_spu_value.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods_sku_spu_value.id
     *
     * @param id the value for xxd_c_goods_sku_spu_value.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods_sku_spu_value.sku_id
     *
     * @return the value of xxd_c_goods_sku_spu_value.sku_id
     *
     * @mbggenerated
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods_sku_spu_value.sku_id
     *
     * @param skuId the value for xxd_c_goods_sku_spu_value.sku_id
     *
     * @mbggenerated
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods_sku_spu_value.spu_value_id
     *
     * @return the value of xxd_c_goods_sku_spu_value.spu_value_id
     *
     * @mbggenerated
     */
    public Integer getSpuValueId() {
        return spuValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods_sku_spu_value.spu_value_id
     *
     * @param spuValueId the value for xxd_c_goods_sku_spu_value.spu_value_id
     *
     * @mbggenerated
     */
    public void setSpuValueId(Integer spuValueId) {
        this.spuValueId = spuValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods_sku_spu_value.stat
     *
     * @return the value of xxd_c_goods_sku_spu_value.stat
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods_sku_spu_value.stat
     *
     * @param stat the value for xxd_c_goods_sku_spu_value.stat
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }
}