package com.xxd.models;

import java.util.Date;

public class XxdCShopBusinessHours {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.monday_starttime
     *
     * @mbggenerated
     */
    private Date mondayStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.tuesday_starttime
     *
     * @mbggenerated
     */
    private Date tuesdayStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.wednesday_starttime
     *
     * @mbggenerated
     */
    private Date wednesdayStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.thursday_starttime
     *
     * @mbggenerated
     */
    private Date thursdayStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.friday_starttime
     *
     * @mbggenerated
     */
    private Date fridayStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.saturday_starttime
     *
     * @mbggenerated
     */
    private Date saturdayStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.sunday_starttime
     *
     * @mbggenerated
     */
    private Date sundayStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.monday_endtime
     *
     * @mbggenerated
     */
    private Date mondayEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.tuesday_endtime
     *
     * @mbggenerated
     */
    private Date tuesdayEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.wednesday_endtime
     *
     * @mbggenerated
     */
    private Date wednesdayEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.thursday_endtime
     *
     * @mbggenerated
     */
    private Date thursdayEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.friday_endtime
     *
     * @mbggenerated
     */
    private Date fridayEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.saturday_endtime
     *
     * @mbggenerated
     */
    private Date saturdayEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_business_hours.sunday_endtime
     *
     * @mbggenerated
     */
    private Date sundayEndtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.id
     *
     * @return the value of xxd_c_shop_business_hours.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.id
     *
     * @param id the value for xxd_c_shop_business_hours.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.monday_starttime
     *
     * @return the value of xxd_c_shop_business_hours.monday_starttime
     *
     * @mbggenerated
     */
    public Date getMondayStarttime() {
        return mondayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.monday_starttime
     *
     * @param mondayStarttime the value for xxd_c_shop_business_hours.monday_starttime
     *
     * @mbggenerated
     */
    public void setMondayStarttime(Date mondayStarttime) {
        this.mondayStarttime = mondayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.tuesday_starttime
     *
     * @return the value of xxd_c_shop_business_hours.tuesday_starttime
     *
     * @mbggenerated
     */
    public Date getTuesdayStarttime() {
        return tuesdayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.tuesday_starttime
     *
     * @param tuesdayStarttime the value for xxd_c_shop_business_hours.tuesday_starttime
     *
     * @mbggenerated
     */
    public void setTuesdayStarttime(Date tuesdayStarttime) {
        this.tuesdayStarttime = tuesdayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.wednesday_starttime
     *
     * @return the value of xxd_c_shop_business_hours.wednesday_starttime
     *
     * @mbggenerated
     */
    public Date getWednesdayStarttime() {
        return wednesdayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.wednesday_starttime
     *
     * @param wednesdayStarttime the value for xxd_c_shop_business_hours.wednesday_starttime
     *
     * @mbggenerated
     */
    public void setWednesdayStarttime(Date wednesdayStarttime) {
        this.wednesdayStarttime = wednesdayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.thursday_starttime
     *
     * @return the value of xxd_c_shop_business_hours.thursday_starttime
     *
     * @mbggenerated
     */
    public Date getThursdayStarttime() {
        return thursdayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.thursday_starttime
     *
     * @param thursdayStarttime the value for xxd_c_shop_business_hours.thursday_starttime
     *
     * @mbggenerated
     */
    public void setThursdayStarttime(Date thursdayStarttime) {
        this.thursdayStarttime = thursdayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.friday_starttime
     *
     * @return the value of xxd_c_shop_business_hours.friday_starttime
     *
     * @mbggenerated
     */
    public Date getFridayStarttime() {
        return fridayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.friday_starttime
     *
     * @param fridayStarttime the value for xxd_c_shop_business_hours.friday_starttime
     *
     * @mbggenerated
     */
    public void setFridayStarttime(Date fridayStarttime) {
        this.fridayStarttime = fridayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.saturday_starttime
     *
     * @return the value of xxd_c_shop_business_hours.saturday_starttime
     *
     * @mbggenerated
     */
    public Date getSaturdayStarttime() {
        return saturdayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.saturday_starttime
     *
     * @param saturdayStarttime the value for xxd_c_shop_business_hours.saturday_starttime
     *
     * @mbggenerated
     */
    public void setSaturdayStarttime(Date saturdayStarttime) {
        this.saturdayStarttime = saturdayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.sunday_starttime
     *
     * @return the value of xxd_c_shop_business_hours.sunday_starttime
     *
     * @mbggenerated
     */
    public Date getSundayStarttime() {
        return sundayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.sunday_starttime
     *
     * @param sundayStarttime the value for xxd_c_shop_business_hours.sunday_starttime
     *
     * @mbggenerated
     */
    public void setSundayStarttime(Date sundayStarttime) {
        this.sundayStarttime = sundayStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.monday_endtime
     *
     * @return the value of xxd_c_shop_business_hours.monday_endtime
     *
     * @mbggenerated
     */
    public Date getMondayEndtime() {
        return mondayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.monday_endtime
     *
     * @param mondayEndtime the value for xxd_c_shop_business_hours.monday_endtime
     *
     * @mbggenerated
     */
    public void setMondayEndtime(Date mondayEndtime) {
        this.mondayEndtime = mondayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.tuesday_endtime
     *
     * @return the value of xxd_c_shop_business_hours.tuesday_endtime
     *
     * @mbggenerated
     */
    public Date getTuesdayEndtime() {
        return tuesdayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.tuesday_endtime
     *
     * @param tuesdayEndtime the value for xxd_c_shop_business_hours.tuesday_endtime
     *
     * @mbggenerated
     */
    public void setTuesdayEndtime(Date tuesdayEndtime) {
        this.tuesdayEndtime = tuesdayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.wednesday_endtime
     *
     * @return the value of xxd_c_shop_business_hours.wednesday_endtime
     *
     * @mbggenerated
     */
    public Date getWednesdayEndtime() {
        return wednesdayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.wednesday_endtime
     *
     * @param wednesdayEndtime the value for xxd_c_shop_business_hours.wednesday_endtime
     *
     * @mbggenerated
     */
    public void setWednesdayEndtime(Date wednesdayEndtime) {
        this.wednesdayEndtime = wednesdayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.thursday_endtime
     *
     * @return the value of xxd_c_shop_business_hours.thursday_endtime
     *
     * @mbggenerated
     */
    public Date getThursdayEndtime() {
        return thursdayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.thursday_endtime
     *
     * @param thursdayEndtime the value for xxd_c_shop_business_hours.thursday_endtime
     *
     * @mbggenerated
     */
    public void setThursdayEndtime(Date thursdayEndtime) {
        this.thursdayEndtime = thursdayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.friday_endtime
     *
     * @return the value of xxd_c_shop_business_hours.friday_endtime
     *
     * @mbggenerated
     */
    public Date getFridayEndtime() {
        return fridayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.friday_endtime
     *
     * @param fridayEndtime the value for xxd_c_shop_business_hours.friday_endtime
     *
     * @mbggenerated
     */
    public void setFridayEndtime(Date fridayEndtime) {
        this.fridayEndtime = fridayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.saturday_endtime
     *
     * @return the value of xxd_c_shop_business_hours.saturday_endtime
     *
     * @mbggenerated
     */
    public Date getSaturdayEndtime() {
        return saturdayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.saturday_endtime
     *
     * @param saturdayEndtime the value for xxd_c_shop_business_hours.saturday_endtime
     *
     * @mbggenerated
     */
    public void setSaturdayEndtime(Date saturdayEndtime) {
        this.saturdayEndtime = saturdayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_business_hours.sunday_endtime
     *
     * @return the value of xxd_c_shop_business_hours.sunday_endtime
     *
     * @mbggenerated
     */
    public Date getSundayEndtime() {
        return sundayEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_business_hours.sunday_endtime
     *
     * @param sundayEndtime the value for xxd_c_shop_business_hours.sunday_endtime
     *
     * @mbggenerated
     */
    public void setSundayEndtime(Date sundayEndtime) {
        this.sundayEndtime = sundayEndtime;
    }
}