package com.xxd.models;

public class XxdCGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods.goodname
     *
     * @mbggenerated
     */
    private String goodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods.photo_id
     *
     * @mbggenerated
     */
    private String photoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods.showmoney
     *
     * @mbggenerated
     */
    private Float showmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods.stat
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_goods.class_id
     *
     * @mbggenerated
     */
    private String classId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods.id
     *
     * @return the value of xxd_c_goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods.id
     *
     * @param id the value for xxd_c_goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods.gid
     *
     * @return the value of xxd_c_goods.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods.gid
     *
     * @param gid the value for xxd_c_goods.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods.goodname
     *
     * @return the value of xxd_c_goods.goodname
     *
     * @mbggenerated
     */
    public String getGoodname() {
        return goodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods.goodname
     *
     * @param goodname the value for xxd_c_goods.goodname
     *
     * @mbggenerated
     */
    public void setGoodname(String goodname) {
        this.goodname = goodname == null ? null : goodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods.photo_id
     *
     * @return the value of xxd_c_goods.photo_id
     *
     * @mbggenerated
     */
    public String getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods.photo_id
     *
     * @param photoId the value for xxd_c_goods.photo_id
     *
     * @mbggenerated
     */
    public void setPhotoId(String photoId) {
        this.photoId = photoId == null ? null : photoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods.showmoney
     *
     * @return the value of xxd_c_goods.showmoney
     *
     * @mbggenerated
     */
    public Float getShowmoney() {
        return showmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods.showmoney
     *
     * @param showmoney the value for xxd_c_goods.showmoney
     *
     * @mbggenerated
     */
    public void setShowmoney(Float showmoney) {
        this.showmoney = showmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods.stat
     *
     * @return the value of xxd_c_goods.stat
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods.stat
     *
     * @param stat the value for xxd_c_goods.stat
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_goods.class_id
     *
     * @return the value of xxd_c_goods.class_id
     *
     * @mbggenerated
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_goods.class_id
     *
     * @param classId the value for xxd_c_goods.class_id
     *
     * @mbggenerated
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }
}