package com.xxd.models;

public class XxdCShopArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_area.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_area.shop_id
     *
     * @mbggenerated
     */
    private String shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_area.area_id
     *
     * @mbggenerated
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop_area.stat
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_area.id
     *
     * @return the value of xxd_c_shop_area.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_area.id
     *
     * @param id the value for xxd_c_shop_area.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_area.shop_id
     *
     * @return the value of xxd_c_shop_area.shop_id
     *
     * @mbggenerated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_area.shop_id
     *
     * @param shopId the value for xxd_c_shop_area.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_area.area_id
     *
     * @return the value of xxd_c_shop_area.area_id
     *
     * @mbggenerated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_area.area_id
     *
     * @param areaId the value for xxd_c_shop_area.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop_area.stat
     *
     * @return the value of xxd_c_shop_area.stat
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop_area.stat
     *
     * @param stat the value for xxd_c_shop_area.stat
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }
}