package com.xxd.models;

import java.math.BigDecimal;

public class XxdCProxyArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area.areaid
     *
     * @mbggenerated
     */
    private String areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area.areaname
     *
     * @mbggenerated
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area.areatype_id
     *
     * @mbggenerated
     */
    private Short areatypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area.longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area.latitude
     *
     * @mbggenerated
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area.protocol
     *
     * @mbggenerated
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area.stat
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area.id
     *
     * @return the value of xxd_c_proxy_area.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area.id
     *
     * @param id the value for xxd_c_proxy_area.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area.areaid
     *
     * @return the value of xxd_c_proxy_area.areaid
     *
     * @mbggenerated
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area.areaid
     *
     * @param areaid the value for xxd_c_proxy_area.areaid
     *
     * @mbggenerated
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid == null ? null : areaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area.areaname
     *
     * @return the value of xxd_c_proxy_area.areaname
     *
     * @mbggenerated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area.areaname
     *
     * @param areaname the value for xxd_c_proxy_area.areaname
     *
     * @mbggenerated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area.areatype_id
     *
     * @return the value of xxd_c_proxy_area.areatype_id
     *
     * @mbggenerated
     */
    public Short getAreatypeId() {
        return areatypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area.areatype_id
     *
     * @param areatypeId the value for xxd_c_proxy_area.areatype_id
     *
     * @mbggenerated
     */
    public void setAreatypeId(Short areatypeId) {
        this.areatypeId = areatypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area.remark
     *
     * @return the value of xxd_c_proxy_area.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area.remark
     *
     * @param remark the value for xxd_c_proxy_area.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area.longitude
     *
     * @return the value of xxd_c_proxy_area.longitude
     *
     * @mbggenerated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area.longitude
     *
     * @param longitude the value for xxd_c_proxy_area.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area.latitude
     *
     * @return the value of xxd_c_proxy_area.latitude
     *
     * @mbggenerated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area.latitude
     *
     * @param latitude the value for xxd_c_proxy_area.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area.protocol
     *
     * @return the value of xxd_c_proxy_area.protocol
     *
     * @mbggenerated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area.protocol
     *
     * @param protocol the value for xxd_c_proxy_area.protocol
     *
     * @mbggenerated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area.stat
     *
     * @return the value of xxd_c_proxy_area.stat
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area.stat
     *
     * @param stat the value for xxd_c_proxy_area.stat
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }
}