package com.xxd.models;

import java.util.Date;

public class XxdCComments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_comments.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_comments.commid
     *
     * @mbggenerated
     */
    private String commid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_comments.good_id
     *
     * @mbggenerated
     */
    private String goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_comments.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_comments.parentid
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_comments.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_comments.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_comments.stat
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_comments.id
     *
     * @return the value of xxd_c_comments.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_comments.id
     *
     * @param id the value for xxd_c_comments.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_comments.commid
     *
     * @return the value of xxd_c_comments.commid
     *
     * @mbggenerated
     */
    public String getCommid() {
        return commid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_comments.commid
     *
     * @param commid the value for xxd_c_comments.commid
     *
     * @mbggenerated
     */
    public void setCommid(String commid) {
        this.commid = commid == null ? null : commid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_comments.good_id
     *
     * @return the value of xxd_c_comments.good_id
     *
     * @mbggenerated
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_comments.good_id
     *
     * @param goodId the value for xxd_c_comments.good_id
     *
     * @mbggenerated
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_comments.user_id
     *
     * @return the value of xxd_c_comments.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_comments.user_id
     *
     * @param userId the value for xxd_c_comments.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_comments.parentid
     *
     * @return the value of xxd_c_comments.parentid
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_comments.parentid
     *
     * @param parentid the value for xxd_c_comments.parentid
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_comments.description
     *
     * @return the value of xxd_c_comments.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_comments.description
     *
     * @param description the value for xxd_c_comments.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_comments.createtime
     *
     * @return the value of xxd_c_comments.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_comments.createtime
     *
     * @param createtime the value for xxd_c_comments.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_comments.stat
     *
     * @return the value of xxd_c_comments.stat
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_comments.stat
     *
     * @param stat the value for xxd_c_comments.stat
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }
}