package com.xxd.models;

public class XxdCPhotos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_photos.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_photos.pid
     *
     * @mbggenerated
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_photos.good_ph_id
     *
     * @mbggenerated
     */
    private String goodPhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_photos.comm_id
     *
     * @mbggenerated
     */
    private String commId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_photos.album
     *
     * @mbggenerated
     */
    private String album;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_photos.hrefaddr
     *
     * @mbggenerated
     */
    private String hrefaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_photos.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_photos.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_photos.id
     *
     * @return the value of xxd_c_photos.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_photos.id
     *
     * @param id the value for xxd_c_photos.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_photos.pid
     *
     * @return the value of xxd_c_photos.pid
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_photos.pid
     *
     * @param pid the value for xxd_c_photos.pid
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_photos.good_ph_id
     *
     * @return the value of xxd_c_photos.good_ph_id
     *
     * @mbggenerated
     */
    public String getGoodPhId() {
        return goodPhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_photos.good_ph_id
     *
     * @param goodPhId the value for xxd_c_photos.good_ph_id
     *
     * @mbggenerated
     */
    public void setGoodPhId(String goodPhId) {
        this.goodPhId = goodPhId == null ? null : goodPhId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_photos.comm_id
     *
     * @return the value of xxd_c_photos.comm_id
     *
     * @mbggenerated
     */
    public String getCommId() {
        return commId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_photos.comm_id
     *
     * @param commId the value for xxd_c_photos.comm_id
     *
     * @mbggenerated
     */
    public void setCommId(String commId) {
        this.commId = commId == null ? null : commId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_photos.album
     *
     * @return the value of xxd_c_photos.album
     *
     * @mbggenerated
     */
    public String getAlbum() {
        return album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_photos.album
     *
     * @param album the value for xxd_c_photos.album
     *
     * @mbggenerated
     */
    public void setAlbum(String album) {
        this.album = album == null ? null : album.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_photos.hrefaddr
     *
     * @return the value of xxd_c_photos.hrefaddr
     *
     * @mbggenerated
     */
    public String getHrefaddr() {
        return hrefaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_photos.hrefaddr
     *
     * @param hrefaddr the value for xxd_c_photos.hrefaddr
     *
     * @mbggenerated
     */
    public void setHrefaddr(String hrefaddr) {
        this.hrefaddr = hrefaddr == null ? null : hrefaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_photos.remark
     *
     * @return the value of xxd_c_photos.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_photos.remark
     *
     * @param remark the value for xxd_c_photos.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_photos.type
     *
     * @return the value of xxd_c_photos.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_photos.type
     *
     * @param type the value for xxd_c_photos.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}