package com.xxd.models;

public class XxdCGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_group.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_group.groupid
     *
     * @mbggenerated
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_group.manager_id
     *
     * @mbggenerated
     */
    private String managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_group.groupname
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_group.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_group.notice
     *
     * @mbggenerated
     */
    private String notice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_group.homegroup
     *
     * @mbggenerated
     */
    private String homegroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_group.stat
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_group.proxynum
     *
     * @mbggenerated
     */
    private Short proxynum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_group.id
     *
     * @return the value of xxd_c_group.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_group.id
     *
     * @param id the value for xxd_c_group.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_group.groupid
     *
     * @return the value of xxd_c_group.groupid
     *
     * @mbggenerated
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_group.groupid
     *
     * @param groupid the value for xxd_c_group.groupid
     *
     * @mbggenerated
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_group.manager_id
     *
     * @return the value of xxd_c_group.manager_id
     *
     * @mbggenerated
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_group.manager_id
     *
     * @param managerId the value for xxd_c_group.manager_id
     *
     * @mbggenerated
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_group.groupname
     *
     * @return the value of xxd_c_group.groupname
     *
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_group.groupname
     *
     * @param groupname the value for xxd_c_group.groupname
     *
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_group.description
     *
     * @return the value of xxd_c_group.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_group.description
     *
     * @param description the value for xxd_c_group.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_group.notice
     *
     * @return the value of xxd_c_group.notice
     *
     * @mbggenerated
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_group.notice
     *
     * @param notice the value for xxd_c_group.notice
     *
     * @mbggenerated
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_group.homegroup
     *
     * @return the value of xxd_c_group.homegroup
     *
     * @mbggenerated
     */
    public String getHomegroup() {
        return homegroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_group.homegroup
     *
     * @param homegroup the value for xxd_c_group.homegroup
     *
     * @mbggenerated
     */
    public void setHomegroup(String homegroup) {
        this.homegroup = homegroup == null ? null : homegroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_group.stat
     *
     * @return the value of xxd_c_group.stat
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_group.stat
     *
     * @param stat the value for xxd_c_group.stat
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_group.proxynum
     *
     * @return the value of xxd_c_group.proxynum
     *
     * @mbggenerated
     */
    public Short getProxynum() {
        return proxynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_group.proxynum
     *
     * @param proxynum the value for xxd_c_group.proxynum
     *
     * @mbggenerated
     */
    public void setProxynum(Short proxynum) {
        this.proxynum = proxynum;
    }
}