package com.xxd.models;

public class XxdCShop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.shopname
     *
     * @mbggenerated
     */
    private String shopname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.addressDetail
     *
     * @mbggenerated
     */
    private String addressdetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.notice
     *
     * @mbggenerated
     */
    private String notice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.stat
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.service_id
     *
     * @mbggenerated
     */
    private Short serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.business_hours_id
     *
     * @mbggenerated
     */
    private Short businessHoursId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.scale
     *
     * @mbggenerated
     */
    private String scale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_shop.reservenotes
     *
     * @mbggenerated
     */
    private String reservenotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.id
     *
     * @return the value of xxd_c_shop.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.id
     *
     * @param id the value for xxd_c_shop.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.sid
     *
     * @return the value of xxd_c_shop.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.sid
     *
     * @param sid the value for xxd_c_shop.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.shopname
     *
     * @return the value of xxd_c_shop.shopname
     *
     * @mbggenerated
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.shopname
     *
     * @param shopname the value for xxd_c_shop.shopname
     *
     * @mbggenerated
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.address
     *
     * @return the value of xxd_c_shop.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.address
     *
     * @param address the value for xxd_c_shop.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.addressDetail
     *
     * @return the value of xxd_c_shop.addressDetail
     *
     * @mbggenerated
     */
    public String getAddressdetail() {
        return addressdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.addressDetail
     *
     * @param addressdetail the value for xxd_c_shop.addressDetail
     *
     * @mbggenerated
     */
    public void setAddressdetail(String addressdetail) {
        this.addressdetail = addressdetail == null ? null : addressdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.longitude
     *
     * @return the value of xxd_c_shop.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.longitude
     *
     * @param longitude the value for xxd_c_shop.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.latitude
     *
     * @return the value of xxd_c_shop.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.latitude
     *
     * @param latitude the value for xxd_c_shop.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.category_id
     *
     * @return the value of xxd_c_shop.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.category_id
     *
     * @param categoryId the value for xxd_c_shop.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.phone
     *
     * @return the value of xxd_c_shop.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.phone
     *
     * @param phone the value for xxd_c_shop.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.notice
     *
     * @return the value of xxd_c_shop.notice
     *
     * @mbggenerated
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.notice
     *
     * @param notice the value for xxd_c_shop.notice
     *
     * @mbggenerated
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.stat
     *
     * @return the value of xxd_c_shop.stat
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.stat
     *
     * @param stat the value for xxd_c_shop.stat
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.service_id
     *
     * @return the value of xxd_c_shop.service_id
     *
     * @mbggenerated
     */
    public Short getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.service_id
     *
     * @param serviceId the value for xxd_c_shop.service_id
     *
     * @mbggenerated
     */
    public void setServiceId(Short serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.business_hours_id
     *
     * @return the value of xxd_c_shop.business_hours_id
     *
     * @mbggenerated
     */
    public Short getBusinessHoursId() {
        return businessHoursId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.business_hours_id
     *
     * @param businessHoursId the value for xxd_c_shop.business_hours_id
     *
     * @mbggenerated
     */
    public void setBusinessHoursId(Short businessHoursId) {
        this.businessHoursId = businessHoursId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.scale
     *
     * @return the value of xxd_c_shop.scale
     *
     * @mbggenerated
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.scale
     *
     * @param scale the value for xxd_c_shop.scale
     *
     * @mbggenerated
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_shop.reservenotes
     *
     * @return the value of xxd_c_shop.reservenotes
     *
     * @mbggenerated
     */
    public String getReservenotes() {
        return reservenotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_shop.reservenotes
     *
     * @param reservenotes the value for xxd_c_shop.reservenotes
     *
     * @mbggenerated
     */
    public void setReservenotes(String reservenotes) {
        this.reservenotes = reservenotes == null ? null : reservenotes.trim();
    }
}