package com.xxd.models;

public class XxdCProxyAreaGood {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area_good.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area_good.area_id
     *
     * @mbggenerated
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area_good.good_id
     *
     * @mbggenerated
     */
    private String goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_c_proxy_area_good.commision
     *
     * @mbggenerated
     */
    private Float commision;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area_good.id
     *
     * @return the value of xxd_c_proxy_area_good.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area_good.id
     *
     * @param id the value for xxd_c_proxy_area_good.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area_good.area_id
     *
     * @return the value of xxd_c_proxy_area_good.area_id
     *
     * @mbggenerated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area_good.area_id
     *
     * @param areaId the value for xxd_c_proxy_area_good.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area_good.good_id
     *
     * @return the value of xxd_c_proxy_area_good.good_id
     *
     * @mbggenerated
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area_good.good_id
     *
     * @param goodId the value for xxd_c_proxy_area_good.good_id
     *
     * @mbggenerated
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_c_proxy_area_good.commision
     *
     * @return the value of xxd_c_proxy_area_good.commision
     *
     * @mbggenerated
     */
    public Float getCommision() {
        return commision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_c_proxy_area_good.commision
     *
     * @param commision the value for xxd_c_proxy_area_good.commision
     *
     * @mbggenerated
     */
    public void setCommision(Float commision) {
        this.commision = commision;
    }
}