package com.xxd.models;

public class XxdGoodsFlash {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_flash.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_flash.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_flash.sta
     *
     * @mbggenerated
     */
    private Short sta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_flash.start_time
     *
     * @mbggenerated
     */
    private String startTime;
    
    private String startTimeHour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_flash.end_time
     *
     * @mbggenerated
     */
    private String endTime;
    
    private String endTimeHour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_flash.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_flash.flash_title
     *
     * @mbggenerated
     */
    private String flashTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_flash.flash_picture
     *
     * @mbggenerated
     */
    private String flashPicture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_flash.id
     *
     * @return the value of xxd_goods_flash.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_flash.id
     *
     * @param id the value for xxd_goods_flash.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_flash.goods_id
     *
     * @return the value of xxd_goods_flash.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_flash.goods_id
     *
     * @param goodsId the value for xxd_goods_flash.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_flash.sta
     *
     * @return the value of xxd_goods_flash.sta
     *
     * @mbggenerated
     */
    public Short getSta() {
        return sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_flash.sta
     *
     * @param sta the value for xxd_goods_flash.sta
     *
     * @mbggenerated
     */
    public void setSta(Short sta) {
        this.sta = sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_flash.start_time
     *
     * @return the value of xxd_goods_flash.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_flash.start_time
     *
     * @param startTime the value for xxd_goods_flash.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_flash.end_time
     *
     * @return the value of xxd_goods_flash.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_flash.end_time
     *
     * @param endTime the value for xxd_goods_flash.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_flash.time
     *
     * @return the value of xxd_goods_flash.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_flash.time
     *
     * @param time the value for xxd_goods_flash.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_flash.flash_title
     *
     * @return the value of xxd_goods_flash.flash_title
     *
     * @mbggenerated
     */
    public String getFlashTitle() {
        return flashTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_flash.flash_title
     *
     * @param flashTitle the value for xxd_goods_flash.flash_title
     *
     * @mbggenerated
     */
    public void setFlashTitle(String flashTitle) {
        this.flashTitle = flashTitle == null ? null : flashTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_flash.flash_picture
     *
     * @return the value of xxd_goods_flash.flash_picture
     *
     * @mbggenerated
     */
    public String getFlashPicture() {
        return flashPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_flash.flash_picture
     *
     * @param flashPicture the value for xxd_goods_flash.flash_picture
     *
     * @mbggenerated
     */
    public void setFlashPicture(String flashPicture) {
        this.flashPicture = flashPicture == null ? null : flashPicture.trim();
    }

	public String getStartTimeHour() {
		return startTimeHour;
	}

	public void setStartTimeHour(String startTimeHour) {
		this.startTimeHour = startTimeHour;
	}

	public String getEndTimeHour() {
		return endTimeHour;
	}

	public void setEndTimeHour(String endTimeHour) {
		this.endTimeHour = endTimeHour;
	}
}