package com.xxd.models;

import java.math.BigDecimal;

public class XxdGoodsPriceGroupBak {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_price_group_bak.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_price_group_bak.goods_group_bak_id
     *
     * @mbggenerated
     */
    private Integer goodsGroupBakId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_price_group_bak.goods_price_stock
     *
     * @mbggenerated
     */
    private Integer goodsPriceStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_price_group_bak.format_name
     *
     * @mbggenerated
     */
    private String formatName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_price_group_bak.market_price
     *
     * @mbggenerated
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_price_group_bak.member_price
     *
     * @mbggenerated
     */
    private BigDecimal memberPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_price_group_bak.group_member_price
     *
     * @mbggenerated
     */
    private BigDecimal groupMemberPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_price_group_bak.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_price_group_bak.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_price_group_bak.goods_price_stock_bak
     *
     * @mbggenerated
     */
    private Integer goodsPriceStockBak;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_price_group_bak.id
     *
     * @return the value of xxd_goods_price_group_bak.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_price_group_bak.id
     *
     * @param id the value for xxd_goods_price_group_bak.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_price_group_bak.goods_group_bak_id
     *
     * @return the value of xxd_goods_price_group_bak.goods_group_bak_id
     *
     * @mbggenerated
     */
    public Integer getGoodsGroupBakId() {
        return goodsGroupBakId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_price_group_bak.goods_group_bak_id
     *
     * @param goodsGroupBakId the value for xxd_goods_price_group_bak.goods_group_bak_id
     *
     * @mbggenerated
     */
    public void setGoodsGroupBakId(Integer goodsGroupBakId) {
        this.goodsGroupBakId = goodsGroupBakId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_price_group_bak.goods_price_stock
     *
     * @return the value of xxd_goods_price_group_bak.goods_price_stock
     *
     * @mbggenerated
     */
    public Integer getGoodsPriceStock() {
        return goodsPriceStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_price_group_bak.goods_price_stock
     *
     * @param goodsPriceStock the value for xxd_goods_price_group_bak.goods_price_stock
     *
     * @mbggenerated
     */
    public void setGoodsPriceStock(Integer goodsPriceStock) {
        this.goodsPriceStock = goodsPriceStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_price_group_bak.format_name
     *
     * @return the value of xxd_goods_price_group_bak.format_name
     *
     * @mbggenerated
     */
    public String getFormatName() {
        return formatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_price_group_bak.format_name
     *
     * @param formatName the value for xxd_goods_price_group_bak.format_name
     *
     * @mbggenerated
     */
    public void setFormatName(String formatName) {
        this.formatName = formatName == null ? null : formatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_price_group_bak.market_price
     *
     * @return the value of xxd_goods_price_group_bak.market_price
     *
     * @mbggenerated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_price_group_bak.market_price
     *
     * @param marketPrice the value for xxd_goods_price_group_bak.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_price_group_bak.member_price
     *
     * @return the value of xxd_goods_price_group_bak.member_price
     *
     * @mbggenerated
     */
    public BigDecimal getMemberPrice() {
        return memberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_price_group_bak.member_price
     *
     * @param memberPrice the value for xxd_goods_price_group_bak.member_price
     *
     * @mbggenerated
     */
    public void setMemberPrice(BigDecimal memberPrice) {
        this.memberPrice = memberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_price_group_bak.group_member_price
     *
     * @return the value of xxd_goods_price_group_bak.group_member_price
     *
     * @mbggenerated
     */
    public BigDecimal getGroupMemberPrice() {
        return groupMemberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_price_group_bak.group_member_price
     *
     * @param groupMemberPrice the value for xxd_goods_price_group_bak.group_member_price
     *
     * @mbggenerated
     */
    public void setGroupMemberPrice(BigDecimal groupMemberPrice) {
        this.groupMemberPrice = groupMemberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_price_group_bak.img
     *
     * @return the value of xxd_goods_price_group_bak.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_price_group_bak.img
     *
     * @param img the value for xxd_goods_price_group_bak.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_price_group_bak.price
     *
     * @return the value of xxd_goods_price_group_bak.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_price_group_bak.price
     *
     * @param price the value for xxd_goods_price_group_bak.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_price_group_bak.goods_price_stock_bak
     *
     * @return the value of xxd_goods_price_group_bak.goods_price_stock_bak
     *
     * @mbggenerated
     */
    public Integer getGoodsPriceStockBak() {
        return goodsPriceStockBak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_price_group_bak.goods_price_stock_bak
     *
     * @param goodsPriceStockBak the value for xxd_goods_price_group_bak.goods_price_stock_bak
     *
     * @mbggenerated
     */
    public void setGoodsPriceStockBak(Integer goodsPriceStockBak) {
        this.goodsPriceStockBak = goodsPriceStockBak;
    }
}