package com.xxd.models;

public class XxdSystemNotification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_system_notification.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_system_notification.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_system_notification.type
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_system_notification.pushTime
     *
     * @mbggenerated
     */
    private String pushtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_system_notification.user_group
     *
     * @mbggenerated
     */
    private Short userGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_system_notification.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_system_notification.id
     *
     * @return the value of xxd_system_notification.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_system_notification.id
     *
     * @param id the value for xxd_system_notification.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_system_notification.title
     *
     * @return the value of xxd_system_notification.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_system_notification.title
     *
     * @param title the value for xxd_system_notification.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_system_notification.type
     *
     * @return the value of xxd_system_notification.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_system_notification.type
     *
     * @param type the value for xxd_system_notification.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_system_notification.pushTime
     *
     * @return the value of xxd_system_notification.pushTime
     *
     * @mbggenerated
     */
    public String getPushtime() {
        return pushtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_system_notification.pushTime
     *
     * @param pushtime the value for xxd_system_notification.pushTime
     *
     * @mbggenerated
     */
    public void setPushtime(String pushtime) {
        this.pushtime = pushtime == null ? null : pushtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_system_notification.user_group
     *
     * @return the value of xxd_system_notification.user_group
     *
     * @mbggenerated
     */
    public Short getUserGroup() {
        return userGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_system_notification.user_group
     *
     * @param userGroup the value for xxd_system_notification.user_group
     *
     * @mbggenerated
     */
    public void setUserGroup(Short userGroup) {
        this.userGroup = userGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_system_notification.content
     *
     * @return the value of xxd_system_notification.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_system_notification.content
     *
     * @param content the value for xxd_system_notification.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	@Override
	public String toString() {
		return "XxdSystemNotification [id=" + id + ", title=" + title + ", type=" + type + ", pushtime=" + pushtime
				+ ", userGroup=" + userGroup + ", content=" + content + "]";
	}
    
    
}